version: '3.3'

services:
    nginx-docker-proxy:
        image: hansehe/nginx-docker-proxy:${VERSION}
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8080:80